# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_rnormParallelization_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_rnormParallelization_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_rnormParallelization_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_rnormParallelization_rcpparma_bothproducts`, x)
}

rNorm_c <- function(length) {
    .Call(`_rnormParallelization_rNorm_c`, length)
}

normal_samples <- function(length, num_vecs) {
    .Call(`_rnormParallelization_normal_samples`, length, num_vecs)
}

